### ISSUE TITLE
V0.6.0 - Calling api.Play() with a context_uri causes an error: 

### ISSUE THREAD

**Issue by Threpio** [brianstrauch/spotify#6]
With the following code (In an attempt to fix issue with [Spotify-Cli #27](https://github.com/brianstrauch/spotify-cli/issues/27):
<img width="854" alt="Screenshot 2021-07-18 at 19 42 30" src="https://user-images.githubusercontent.com/49570057/126077054-a2034f73-dc35-464e-91d5-3e1a0b558627.png">

The error is returned as this - It seems that even when passing no query my logic is off?
<img width="896" alt="Screenshot 2021-07-18 at 19 42 35" src="https://user-images.githubusercontent.com/49570057/126077060-ebba878a-5ea6-438a-b126-318411d8b534.png">

**Comment by brianstrauch** [comment]
@Threpio The issue is that the last two calls to `Play()` are passing `""` as the URI. Instead, remove that argument. For variadic arguments, you can pass 0 arguments!

**Comment by Threpio** [comment]
Yup - Didn't notice that untill I passed 0 arguments and it was fine.
